### ISSUE TITLE
Transaction pool & "dirty" transactions

### ISSUE THREAD

**Issue by BoJacobs** [neozo-software/jblockchain#4]
Hi! I had a look at your project and had a question about the following:

https://github.com/neozo-software/jblockchain/blob/0232c6475e5240b0cd99a9b3699ac831fba22e91/node/src/main/java/de/neozo/jblockchain/node/service/BlockService.java#L48-L62

After appending the block, the transactions are removed from the nodes' transaction pool. Is there anyway that the other nodes are informed that these transactions are processed? And if so, what if another node is currently processing those transactions as well?  

Thanks!

**Comment by RolandColored** [comment]
Hi. The removal from the transaction pool happens in the method you mentioned. The key is that this method is invoked on each node, because the successful miner will inform all other nodes about it's newly found block.


> And if so, what if another node is currently processing those transactions as well?

Yes this might be the case. The current implementation won't handle this case and let the MiningService trying to mine a block with transactions which are already processed - all for nothing. A fix would be to restart the current mining operation so it would pull new transactions from the pool.

**Comment by BoJacobs** [comment]
Thanks for the quick reply! 
 > The key is that this method is invoked on each node, because the successful miner will inform all other nodes about it's newly found block.

Ofcourse, I completely missed that!

 > A fix would be to restart the current mining operation so it would pull new transactions from the pool. 

That would work! Seems like there are a lot of ways to tackle this issue.

Your implementation is very useful to get to know some of the blockchain principles, thanks!
